var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/account/set-default-address/route.js")
R.c("server/chunks/_3c6ba809._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__068c984e._.js")
R.c("server/chunks/node_modules_@upstash_redis_nodejs_mjs_85cd95da._.js")
R.c("server/chunks/[root-of-the-server]__3026ce34._.js")
R.c("server/chunks/_f15003fe._.js")
R.c("server/chunks/src_lib_ea5dd9ae._.js")
R.c("server/chunks/_next-internal_server_app_api_account_set-default-address_route_actions_5d3ef0bc.js")
R.m(71753)
module.exports=R.m(71753).exports
