var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/dev/email/send-test/route.js")
R.c("server/chunks/[root-of-the-server]__e9a808e4._.js")
R.c("server/chunks/_f15003fe._.js")
R.c("server/chunks/[root-of-the-server]__559727e9._.js")
R.c("server/chunks/[root-of-the-server]__b3b04900._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__e48e7fd3._.js")
R.c("server/chunks/_next-internal_server_app_api_dev_email_send-test_route_actions_4ba3688d.js")
R.m(71422)
module.exports=R.m(71422).exports
