/* Inventory every hardcoded colour utility in the codebase so the dark-mode
   patch layer in globals.css can be generated by luminance class instead of
   guessed at. Emits tmp/dark-inventory.json. */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const SRC = path.join(ROOT, "src");

function walk(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) {
      if (e.name === "node_modules" || e.name === ".next") continue;
      walk(p, out);
    } else if (/\.(tsx|ts|jsx|js)$/.test(e.name)) out.push(p);
  }
  return out;
}

// property prefix -> regex fragment capturing the colour token
const PROPS = [
  "bg", "text", "border", "from", "via", "to", "ring",
  "fill", "stroke", "decoration", "outline", "shadow", "divide", "placeholder",
];

const hexRe = new RegExp(
  `\\b(${PROPS.join("|")})-\\[#([0-9a-fA-F]{3,8})\\](?!/)`,
  "g"
);

// rgb()/rgba() and var()-based arbitrary colours
const rgbRe = new RegExp(
  `\\b(${PROPS.join("|")})-\\[(rgba?\\([^\\]]+\\))\\]`,
  "g"
);
const varRe = new RegExp(
  `\\b(${PROPS.join("|")})-\\[var\\([^\\]]+\\)\\]`,
  "g"
);
// tailwind slash-opacity forms e.g. bg-white/20, bg-black/30
const slashRe = /\b(bg|text|border|from|via|to|ring)-(white|black)\/(\d+)/g;
const grayRe =
  /\b(bg|text|border|from|via|to|ring|divide)-(gray|slate|zinc|neutral|stone)-(50|100|200|300|400|500|600|700|800|900)\b/g;
// hex WITH an alpha suffix, e.g. bg-[#dbe8d7]/35 -- needs its own rule because
// the alpha is a tint over whatever is behind, not a solid surface.
const hexAlphaRe = new RegExp(
  `\\b(${PROPS.join("|")})-\\[#([0-9a-fA-F]{3,8})\\]/(\\d+|\\[[0-9.]+\\])`,
  "g"
);
/* Variant-prefixed literals (`hover:bg-[#f8fbf7]`, `focus:ring-[#6f9878]`).
   These matter because Tailwind emits them as `.hover\:bg-[#f8fbf7]:hover`, so a
   plain `.bg-[#f8fbf7]` rule in the dark layer cannot reach them -- and an
   unhandled light hover flashes bright white on a dark card. */
const variantRe =
  /\b((?:hover|focus|focus-visible|focus-within|active|disabled):(?:bg|text|border|ring|divide|fill)-(?:\[#[0-9a-fA-F]{3,8}\]|\[rgba?\([^\]]+\)\]|white\/\d+|black\/\d+))/g;
/* Explicit dark-mode utilities the developers already wrote. These are the
   app's own dark design system and my generated layer must never override
   them, so they are collected here and re-asserted after the remap. */
const darkRe =
  /\bdark:(?:(?:hover|focus|focus-visible|focus-within|active|disabled):)?(?:bg|text|border|ring|divide|fill)-(?:\[#[0-9a-fA-F]{3,8}\]|\[rgba?\([^\]]+\)\]|white(?:\/\d+)?|black(?:\/\d+)?|[a-z]+-\d{2,3})(?:\/\d+)?/g;



/* Arbitrary background GRADIENTS need a balanced-bracket scan -- the value
   contains nested parens and commas, which a regex cannot match reliably. */
function extractGradients(src, out) {
  const needle = /(?:bg|from|via|to)-\[(?:linear|radial|conic)-gradient\(/g;
  let m;
  while ((m = needle.exec(src))) {
    const tokenStart = m.index;
    const open = src.indexOf("[", tokenStart);
    if (open < 0) continue;
    // walk forward tracking bracket nesting to find the true closing "]"
    let depth = 0, closed = -1;
    for (let i = open; i < src.length; i++) {
      const ch = src[i];
      if (ch === "[") depth++;
      else if (ch === "]") {
        depth--;
        if (depth === 0) { closed = i; break; }
      }
    }
    if (closed < 0) continue;
    const value = src.slice(tokenStart, closed + 1);
    needle.lastIndex = closed + 1;
    if (value.length > 400) continue;
    if (!out[value]) out[value] = { count: 0, files: new Set() };
    out[value].count++;
  }
}

const files = walk(SRC);
const inventory = {
  hex: {},      // "bg-#fafbf9" -> { count, files:Set }
  rgb: {},
  var: {},
  slash: {},
  gray: {},
  hexAlpha: {}, // "bg-[#dbe8d7]/35" -> { count, files:Set }
  grad: {},     // "bg-[linear-gradient(...)]" -> { count, files:Set }
  variant: {},  // "hover:bg-[#f8fbf7]" -> { count, files:Set }
  darkUtils: {}, // "dark:bg-[#0a1420]" -> { count, files:Set }
  filesScanned: files.length,
};

function bump(bucket, key, file) {
  if (!inventory[bucket][key]) inventory[bucket][key] = { count: 0, files: new Set() };
  inventory[bucket][key].count++;
  inventory[bucket][key].files.add(path.relative(ROOT, file).replace(/\\/g, "/"));
}

for (const f of files) {
  const src = fs.readFileSync(f, "utf8");
  let m;
  hexRe.lastIndex = 0;
  while ((m = hexRe.exec(src))) bump("hex", `${m[1]}-#${m[2].toLowerCase()}`, f);
  rgbRe.lastIndex = 0;
  while ((m = rgbRe.exec(src))) bump("rgb", `${m[1]}-[${m[2]}]`, f);
  varRe.lastIndex = 0;
  while ((m = varRe.exec(src))) bump("var", m[0], f);
  slashRe.lastIndex = 0;
  while ((m = slashRe.exec(src))) bump("slash", `${m[1]}-${m[2]}/${m[3]}`, f);
  grayRe.lastIndex = 0;
  while ((m = grayRe.exec(src))) bump("gray", m[0], f);
  hexAlphaRe.lastIndex = 0;
  while ((m = hexAlphaRe.exec(src))) bump("hexAlpha", `${m[1]}-[#${m[2].toLowerCase()}]/${m[3]}`, f);
  variantRe.lastIndex = 0;
  while ((m = variantRe.exec(src))) bump("variant", m[1], f);
  darkRe.lastIndex = 0;
  while ((m = darkRe.exec(src))) bump("darkUtils", m[0], f);
  extractGradients(src, inventory.grad);
}

// ---- luminance classification -------------------------------------------
function toRgb(hex) {
  let h = hex.replace("#", "");
  if (h.length === 3) h = h.split("").map((c) => c + c).join("");
  if (h.length === 8) h = h.slice(0, 6);
  if (h.length !== 6) return null;
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16));
}
function luminance(hex) {
  const rgb = toRgb(hex);
  if (!rgb) return null;
  // WCAG relative luminance
  const [r, g, b] = rgb.map((v) => {
    const s = v / 255;
    return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}
function relLum(hex) {
  // simple perceptual luma 0..255 for bucketing
  const rgb = toRgb(hex);
  if (!rgb) return null;
  return 0.299 * rgb[0] + 0.587 * rgb[1] + 0.114 * rgb[2];
}
function sat(hex) {
  const rgb = toRgb(hex);
  if (!rgb) return null;
  const max = Math.max(...rgb), min = Math.min(...rgb);
  return max === 0 ? 0 : (max - min) / max;
}

const hexList = Object.entries(inventory.hex).map(([k, v]) => {
  const [prop, hex] = k.split("-");
  return {
    prop, hex,
    luma: Math.round(relLum(hex) ?? -1),
    sat: +(sat(hex) ?? 0).toFixed(2),
    count: v.count,
    files: [...v.files],
  };
});
hexList.sort((a, b) => a.prop.localeCompare(b.prop) || a.luma - b.luma);

const out = {
  filesScanned: inventory.filesScanned,
  hex: hexList,
  rgb: Object.fromEntries(Object.entries(inventory.rgb).map(([k, v]) => [k, { count: v.count, files: [...v.files] }])),
  var: Object.fromEntries(Object.entries(inventory.var).map(([k, v]) => [k, { count: v.count, files: [...v.files] }])),
  slash: Object.fromEntries(Object.entries(inventory.slash).map(([k, v]) => [k, { count: v.count, files: [...v.files] }])),
  gray: Object.fromEntries(Object.entries(inventory.gray).map(([k, v]) => [k, { count: v.count, files: [...v.files] }])),
  hexAlpha: Object.entries(inventory.hexAlpha)
    .map(([k, v]) => ({ key: k, count: v.count, files: [...v.files] }))
    .sort((a, b) => b.count - a.count),
  grad: Object.entries(inventory.grad)
    .map(([k, v]) => ({ key: k, count: v.count, files: [...v.files] }))
    .sort((a, b) => b.count - a.count),
  variant: Object.entries(inventory.variant)
    .map(([k, v]) => ({ key: k, count: v.count, files: [...v.files] }))
    .sort((a, b) => b.count - a.count),
  darkUtils: Object.entries(inventory.darkUtils)
    .map(([k, v]) => ({ key: k, count: v.count, files: [...v.files] }))
    .sort((a, b) => b.count - a.count),
};

fs.writeFileSync(path.join(__dirname, "dark-inventory.json"), JSON.stringify(out, null, 1));

// ---- console report -------------------------------------------------------
console.log(`files scanned: ${out.filesScanned}`);
console.log(`distinct hex utilities: ${hexList.length}`);
for (const prop of ["bg", "text", "border", "from", "via", "to", "ring", "fill", "stroke"]) {
  const rows = hexList.filter((r) => r.prop === prop);
  if (!rows.length) continue;
  console.log(`\n[${prop}] ${rows.length} distinct`);
}
console.log(`\nrgb() arbitrary: ${Object.keys(out.rgb).length}`);
console.log(`var() arbitrary: ${Object.keys(out.var).length}`);
console.log(`white/black slash: ${Object.keys(out.slash).length}`);
console.log(`gray scale utils: ${Object.keys(out.gray).length}`);
console.log(`hex+alpha utils: ${out.hexAlpha.length}`);
console.log(`arbitrary gradient bgs: ${out.grad.length}`);
console.log(`variant-prefixed literals: ${out.variant.length}`);
