var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/orders/create-shipment/route.js")
R.c("server/chunks/[root-of-the-server]__068c984e._.js")
R.c("server/chunks/src_lib_order-email_ts_cae750c9._.js")
R.c("server/chunks/src_lib_shipping_ts_318a842c._.js")
R.c("server/chunks/src_lib_ea5dd9ae._.js")
R.c("server/chunks/src_lib_8e497ff8._.js")
R.c("server/chunks/[root-of-the-server]__b3b04900._.js")
R.c("server/chunks/node_modules_@upstash_redis_nodejs_mjs_85cd95da._.js")
R.c("server/chunks/_f15003fe._.js")
R.c("server/chunks/[root-of-the-server]__3026ce34._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__f785066c._.js")
R.c("server/chunks/ce889_server_app_api_admin_orders_create-shipment_route_actions_8efa7134.js")
R.m(2788)
module.exports=R.m(2788).exports
