var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/articles/[id]/route.js")
R.c("server/chunks/_ee14f3a4._.js")
R.c("server/chunks/_f15003fe._.js")
R.c("server/chunks/[root-of-the-server]__e9a808e4._.js")
R.c("server/chunks/node_modules_next_afec86a9._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__e48e7fd3._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_articles_[id]_route_actions_8d8fb164.js")
R.m(46176)
module.exports=R.m(46176).exports
