var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/cron/blog-automation/route.js")
R.c("server/chunks/src_lib_68270f20._.js")
R.c("server/chunks/_f15003fe._.js")
R.c("server/chunks/[root-of-the-server]__e9a808e4._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_next_afec86a9._.js")
R.c("server/chunks/[root-of-the-server]__e48e7fd3._.js")
R.c("server/chunks/_d821db9a._.js")
R.c("server/chunks/_next-internal_server_app_api_cron_blog-automation_route_actions_d0d2039c.js")
R.m(40111)
module.exports=R.m(40111).exports
