var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/products/route.js")
R.c("server/chunks/src_lib_admin-auth_ts_0446f202._.js")
R.c("server/chunks/[root-of-the-server]__e9a808e4._.js")
R.c("server/chunks/_aff30f82._.js")
R.c("server/chunks/[root-of-the-server]__e48e7fd3._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_f15003fe._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_products_route_actions_d5c72fbf.js")
R.m(3976)
module.exports=R.m(3976).exports
