var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/products/bulk/route.js")
R.c("server/chunks/_f58f1824._.js")
R.c("server/chunks/src_lib_ea5dd9ae._.js")
R.c("server/chunks/[root-of-the-server]__8b59ce6e._.js")
R.c("server/chunks/[root-of-the-server]__3026ce34._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_@upstash_redis_nodejs_mjs_85cd95da._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_products_bulk_route_actions_3cd5a2f0.js")
R.m(71321)
module.exports=R.m(71321).exports
