var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/test-orders/route.js")
R.c("server/chunks/[root-of-the-server]__e9a808e4._.js")
R.c("server/chunks/_f15003fe._.js")
R.c("server/chunks/[root-of-the-server]__096df6db._.js")
R.c("server/chunks/[root-of-the-server]__b3b04900._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__e48e7fd3._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_test-orders_route_actions_51035e2f.js")
R.m(98800)
module.exports=R.m(98800).exports
