var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/reset-password/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__e13ba328._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_eb02d2bc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__530b55fd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1220a8a4._.js")
R.c("server/chunks/ssr/node_modules_861e98fe._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_66f71be5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3558acf3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_reset-password_page_actions_f3021308.js")
R.m(52767)
module.exports=R.m(52767).exports
