var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/orders/route.js")
R.c("server/chunks/[root-of-the-server]__e9a808e4._.js")
R.c("server/chunks/_f15003fe._.js")
R.c("server/chunks/[root-of-the-server]__b8ce4db8._.js")
R.c("server/chunks/[root-of-the-server]__b3b04900._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__e48e7fd3._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_orders_route_actions_8a3386f9.js")
R.m(99217)
module.exports=R.m(99217).exports
