// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account" | "/account/orders" | "/account/orders/[order]" | "/admin" | "/admin/automation" | "/admin/delhivery" | "/admin/orders/[id]" | "/admin/products" | "/cart" | "/checkout" | "/collections" | "/collections/[collectionHandle]" | "/collections/[collectionHandle]/[plantHandle]" | "/collections/beginner-friendly" | "/collections/cactus" | "/collections/pots" | "/collections/succulents" | "/collections/succulents-under-40" | "/collections/succulents/[handle]" | "/combo" | "/combo-builder" | "/contact" | "/forgot-password" | "/login" | "/offline" | "/order-placed" | "/order-tracker" | "/plant-care" | "/plant-care/[handle]" | "/policies" | "/privacy-policy" | "/products/[handle]" | "/refund-policy" | "/reset-password" | "/shipping-returns" | "/shop" | "/signup" | "/terms-and-conditions" | "/wishlist"
type AppRouteHandlerRoutes = "/api/account/add-address" | "/api/account/delete-address" | "/api/account/set-default-address" | "/api/account/update-address" | "/api/account/update-password" | "/api/account/update-profile" | "/api/admin/articles" | "/api/admin/articles/[id]" | "/api/admin/articles/pin-order" | "/api/admin/automation/topics" | "/api/admin/blog-prompt" | "/api/admin/customers/[id]" | "/api/admin/dashboard" | "/api/admin/delhivery/manual-order" | "/api/admin/email" | "/api/admin/generate-blog" | "/api/admin/media" | "/api/admin/orders" | "/api/admin/orders/[id]" | "/api/admin/orders/create-shipment" | "/api/admin/orders/resend-confirmation" | "/api/admin/orders/status" | "/api/admin/products" | "/api/admin/products/[id]" | "/api/admin/products/bulk" | "/api/admin/revalidate-blog" | "/api/admin/reviews" | "/api/admin/test-orders" | "/api/auth/session" | "/api/blog-translate" | "/api/chat" | "/api/checkout" | "/api/cron/blog-automation" | "/api/customer" | "/api/dev/email/send-test" | "/api/filters" | "/api/forgot-password" | "/api/login" | "/api/logout" | "/api/media/[id]" | "/api/meta/catalog" | "/api/meta/catalog/generate" | "/api/newsletter/subscribe" | "/api/order-tracker/lookup" | "/api/order-tracker/redirect" | "/api/pincode-serviceability" | "/api/plant-suggestions" | "/api/products" | "/api/razorpay/create-order" | "/api/razorpay/status" | "/api/razorpay/verify" | "/api/razorpay/webhook" | "/api/recommendations" | "/api/reset-password" | "/api/reviews/delete" | "/api/reviews/edit" | "/api/reviews/submit" | "/api/search" | "/api/shipments/process" | "/api/signup" | "/api/track-order" | "/api/wallet/release-hold" | "/api/wishlist"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/account": {}
  "/account/orders": {}
  "/account/orders/[order]": { "order": string; }
  "/admin": {}
  "/admin/automation": {}
  "/admin/delhivery": {}
  "/admin/orders/[id]": { "id": string; }
  "/admin/products": {}
  "/api/account/add-address": {}
  "/api/account/delete-address": {}
  "/api/account/set-default-address": {}
  "/api/account/update-address": {}
  "/api/account/update-password": {}
  "/api/account/update-profile": {}
  "/api/admin/articles": {}
  "/api/admin/articles/[id]": { "id": string; }
  "/api/admin/articles/pin-order": {}
  "/api/admin/automation/topics": {}
  "/api/admin/blog-prompt": {}
  "/api/admin/customers/[id]": { "id": string; }
  "/api/admin/dashboard": {}
  "/api/admin/delhivery/manual-order": {}
  "/api/admin/email": {}
  "/api/admin/generate-blog": {}
  "/api/admin/media": {}
  "/api/admin/orders": {}
  "/api/admin/orders/[id]": { "id": string; }
  "/api/admin/orders/create-shipment": {}
  "/api/admin/orders/resend-confirmation": {}
  "/api/admin/orders/status": {}
  "/api/admin/products": {}
  "/api/admin/products/[id]": { "id": string; }
  "/api/admin/products/bulk": {}
  "/api/admin/revalidate-blog": {}
  "/api/admin/reviews": {}
  "/api/admin/test-orders": {}
  "/api/auth/session": {}
  "/api/blog-translate": {}
  "/api/chat": {}
  "/api/checkout": {}
  "/api/cron/blog-automation": {}
  "/api/customer": {}
  "/api/dev/email/send-test": {}
  "/api/filters": {}
  "/api/forgot-password": {}
  "/api/login": {}
  "/api/logout": {}
  "/api/media/[id]": { "id": string; }
  "/api/meta/catalog": {}
  "/api/meta/catalog/generate": {}
  "/api/newsletter/subscribe": {}
  "/api/order-tracker/lookup": {}
  "/api/order-tracker/redirect": {}
  "/api/pincode-serviceability": {}
  "/api/plant-suggestions": {}
  "/api/products": {}
  "/api/razorpay/create-order": {}
  "/api/razorpay/status": {}
  "/api/razorpay/verify": {}
  "/api/razorpay/webhook": {}
  "/api/recommendations": {}
  "/api/reset-password": {}
  "/api/reviews/delete": {}
  "/api/reviews/edit": {}
  "/api/reviews/submit": {}
  "/api/search": {}
  "/api/shipments/process": {}
  "/api/signup": {}
  "/api/track-order": {}
  "/api/wallet/release-hold": {}
  "/api/wishlist": {}
  "/cart": {}
  "/checkout": {}
  "/collections": {}
  "/collections/[collectionHandle]": { "collectionHandle": string; }
  "/collections/[collectionHandle]/[plantHandle]": { "collectionHandle": string; "plantHandle": string; }
  "/collections/beginner-friendly": {}
  "/collections/cactus": {}
  "/collections/pots": {}
  "/collections/succulents": {}
  "/collections/succulents-under-40": {}
  "/collections/succulents/[handle]": { "handle": string; }
  "/combo": {}
  "/combo-builder": {}
  "/contact": {}
  "/forgot-password": {}
  "/login": {}
  "/offline": {}
  "/order-placed": {}
  "/order-tracker": {}
  "/plant-care": {}
  "/plant-care/[handle]": { "handle": string; }
  "/policies": {}
  "/privacy-policy": {}
  "/products/[handle]": { "handle": string; }
  "/refund-policy": {}
  "/reset-password": {}
  "/shipping-returns": {}
  "/shop": {}
  "/signup": {}
  "/terms-and-conditions": {}
  "/wishlist": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
