// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/orders/[order]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/orders/[order]">> = Specific
  const handler = {} as typeof import("../../src/app/account/orders/[order]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/orders">> = Specific
  const handler = {} as typeof import("../../src/app/account/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/automation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/automation">> = Specific
  const handler = {} as typeof import("../../src/app/admin/automation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products">> = Specific
  const handler = {} as typeof import("../../src/app/admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../src/app/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/collections/[collectionHandle]/[plantHandle]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections/[collectionHandle]/[plantHandle]">> = Specific
  const handler = {} as typeof import("../../src/app/collections/[collectionHandle]/[plantHandle]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/collections/[collectionHandle]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections/[collectionHandle]">> = Specific
  const handler = {} as typeof import("../../src/app/collections/[collectionHandle]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/collections/beginner-friendly/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections/beginner-friendly">> = Specific
  const handler = {} as typeof import("../../src/app/collections/beginner-friendly/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/collections/cactus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections/cactus">> = Specific
  const handler = {} as typeof import("../../src/app/collections/cactus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/collections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections">> = Specific
  const handler = {} as typeof import("../../src/app/collections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/collections/pots/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections/pots">> = Specific
  const handler = {} as typeof import("../../src/app/collections/pots/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/collections/succulents-under-40/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections/succulents-under-40">> = Specific
  const handler = {} as typeof import("../../src/app/collections/succulents-under-40/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/collections/succulents/[handle]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections/succulents/[handle]">> = Specific
  const handler = {} as typeof import("../../src/app/collections/succulents/[handle]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/collections/succulents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections/succulents">> = Specific
  const handler = {} as typeof import("../../src/app/collections/succulents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/combo-builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/combo-builder">> = Specific
  const handler = {} as typeof import("../../src/app/combo-builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/combo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/combo">> = Specific
  const handler = {} as typeof import("../../src/app/combo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/order-placed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/order-placed">> = Specific
  const handler = {} as typeof import("../../src/app/order-placed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/order-tracker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/order-tracker">> = Specific
  const handler = {} as typeof import("../../src/app/order-tracker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/plant-care/[handle]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plant-care/[handle]">> = Specific
  const handler = {} as typeof import("../../src/app/plant-care/[handle]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/plant-care/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plant-care">> = Specific
  const handler = {} as typeof import("../../src/app/plant-care/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/policies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/policies">> = Specific
  const handler = {} as typeof import("../../src/app/policies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/[handle]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/[handle]">> = Specific
  const handler = {} as typeof import("../../src/app/products/[handle]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/refund-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/refund-policy">> = Specific
  const handler = {} as typeof import("../../src/app/refund-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shipping-returns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shipping-returns">> = Specific
  const handler = {} as typeof import("../../src/app/shipping-returns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop">> = Specific
  const handler = {} as typeof import("../../src/app/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms-and-conditions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-and-conditions">> = Specific
  const handler = {} as typeof import("../../src/app/terms-and-conditions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wishlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wishlist">> = Specific
  const handler = {} as typeof import("../../src/app/wishlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/add-address/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/add-address">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/add-address/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/delete-address/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/delete-address">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/delete-address/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/set-default-address/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/set-default-address">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/set-default-address/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/update-address/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/update-address">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/update-address/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/update-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/update-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/update-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/update-profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/update-profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/update-profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/articles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/articles/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/articles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/articles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/articles">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/articles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/automation/topics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/automation/topics">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/automation/topics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/customers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/customers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/customers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/email">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/generate-blog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/generate-blog">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/generate-blog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/media">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/orders/create-shipment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders/create-shipment">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/orders/create-shipment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/orders/resend-confirmation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders/resend-confirmation">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/orders/resend-confirmation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/products/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/products/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/products/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/products/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/test-orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/test-orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/test-orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blog-translate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog-translate">> = Specific
  const handler = {} as typeof import("../../src/app/api/blog-translate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/blog-automation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/blog-automation">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/blog-automation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev/email/send-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/email/send-test">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev/email/send-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/filters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/filters">> = Specific
  const handler = {} as typeof import("../../src/app/api/filters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/media/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/media/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meta/catalog/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/catalog/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/meta/catalog/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meta/catalog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/catalog">> = Specific
  const handler = {} as typeof import("../../src/app/api/meta/catalog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/newsletter/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/newsletter/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/newsletter/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/order-tracker/lookup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/order-tracker/lookup">> = Specific
  const handler = {} as typeof import("../../src/app/api/order-tracker/lookup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/order-tracker/redirect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/order-tracker/redirect">> = Specific
  const handler = {} as typeof import("../../src/app/api/order-tracker/redirect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pincode-serviceability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pincode-serviceability">> = Specific
  const handler = {} as typeof import("../../src/app/api/pincode-serviceability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/plant-suggestions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plant-suggestions">> = Specific
  const handler = {} as typeof import("../../src/app/api/plant-suggestions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/razorpay/create-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/razorpay/create-order">> = Specific
  const handler = {} as typeof import("../../src/app/api/razorpay/create-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/razorpay/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/razorpay/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/razorpay/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/razorpay/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/razorpay/verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/razorpay/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/razorpay/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/razorpay/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/razorpay/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recommendations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recommendations">> = Specific
  const handler = {} as typeof import("../../src/app/api/recommendations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reviews/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews/delete">> = Specific
  const handler = {} as typeof import("../../src/app/api/reviews/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reviews/edit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews/edit">> = Specific
  const handler = {} as typeof import("../../src/app/api/reviews/edit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reviews/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/reviews/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/shipments/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shipments/process">> = Specific
  const handler = {} as typeof import("../../src/app/api/shipments/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/track-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/track-order">> = Specific
  const handler = {} as typeof import("../../src/app/api/track-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wallet/release-hold/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet/release-hold">> = Specific
  const handler = {} as typeof import("../../src/app/api/wallet/release-hold/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wishlist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wishlist">> = Specific
  const handler = {} as typeof import("../../src/app/api/wishlist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
