var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/customers/[id]/route.js")
R.c("server/chunks/_3ea66387._.js")
R.c("server/chunks/_f15003fe._.js")
R.c("server/chunks/[root-of-the-server]__068c984e._.js")
R.c("server/chunks/node_modules_@upstash_redis_nodejs_mjs_85cd95da._.js")
R.c("server/chunks/[root-of-the-server]__3026ce34._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/src_lib_ea5dd9ae._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_customers_[id]_route_actions_743fea90.js")
R.m(55132)
module.exports=R.m(55132).exports
