var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/collections/[collectionHandle]/[plantHandle]/page.js")
R.c("server/chunks/ssr/node_modules_next_dist_fb290741._.js")
R.c("server/chunks/ssr/_1993f15a._.js")
R.c("server/chunks/ssr/src_lib_19694aee._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__27187cfc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__19507de2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1220a8a4._.js")
R.c("server/chunks/ssr/node_modules_861e98fe._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_66f71be5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__13b4c230._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/ce889_server_app_collections_[collectionHandle]_[plantHandle]_page_actions_1fd8d8d2.js")
R.m(84939)
module.exports=R.m(84939).exports
