var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/articles/route.js")
R.c("server/chunks/_472811e5._.js")
R.c("server/chunks/_f15003fe._.js")
R.c("server/chunks/[root-of-the-server]__e9a808e4._.js")
R.c("server/chunks/node_modules_next_afec86a9._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__e48e7fd3._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_articles_route_actions_c757fa12.js")
R.m(99797)
module.exports=R.m(99797).exports
