var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/recommendations/route.js")
R.c("server/chunks/[root-of-the-server]__8b59ce6e._.js")
R.c("server/chunks/src_lib_ea5dd9ae._.js")
R.c("server/chunks/_1d7ef832._.js")
R.c("server/chunks/[root-of-the-server]__3026ce34._.js")
R.c("server/chunks/node_modules_@upstash_redis_nodejs_mjs_85cd95da._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_next-internal_server_app_api_recommendations_route_actions_b608ab2e.js")
R.m(43583)
module.exports=R.m(43583).exports
