var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/razorpay/webhook/route.js")
R.c("server/chunks/[root-of-the-server]__0045af7d._.js")
R.c("server/chunks/src_lib_shipping_ts_318a842c._.js")
R.c("server/chunks/src_lib_order-email_ts_cae750c9._.js")
R.c("server/chunks/[root-of-the-server]__b40ce2e2._.js")
R.c("server/chunks/[root-of-the-server]__3026ce34._.js")
R.c("server/chunks/[root-of-the-server]__b3b04900._.js")
R.c("server/chunks/src_lib_8e497ff8._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_next-internal_server_app_api_razorpay_webhook_route_actions_a5e7a5b4.js")
R.m(46266)
module.exports=R.m(46266).exports
