var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/razorpay/create-order/route.js")
R.c("server/chunks/[root-of-the-server]__b69e1414._.js")
R.c("server/chunks/_f15003fe._.js")
R.c("server/chunks/[root-of-the-server]__e9a808e4._.js")
R.c("server/chunks/[root-of-the-server]__e48e7fd3._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__b3b04900._.js")
R.c("server/chunks/[root-of-the-server]__4873a0f4._.js")
R.c("server/chunks/_next-internal_server_app_api_razorpay_create-order_route_actions_795bb92b.js")
R.m(30051)
module.exports=R.m(30051).exports
