var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/policies/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__fea23714._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_bcae4344._.js")
R.c("server/chunks/ssr/[root-of-the-server]__19507de2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1220a8a4._.js")
R.c("server/chunks/ssr/node_modules_861e98fe._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_66f71be5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__13b4c230._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_policies_page_actions_4bd69a7d.js")
R.m(94102)
module.exports=R.m(94102).exports
