var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/order-tracker/lookup/route.js")
R.c("server/chunks/src_lib_delhivery_ts_fca7f641._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__8b59ce6e._.js")
R.c("server/chunks/[root-of-the-server]__3026ce34._.js")
R.c("server/chunks/node_modules_@upstash_redis_nodejs_mjs_85cd95da._.js")
R.c("server/chunks/src_lib_ea5dd9ae._.js")
R.c("server/chunks/_fe6f7635._.js")
R.c("server/chunks/_next-internal_server_app_api_order-tracker_lookup_route_actions_63325998.js")
R.m(11957)
module.exports=R.m(11957).exports
