var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/search/route.js")
R.c("server/chunks/[root-of-the-server]__8b59ce6e._.js")
R.c("server/chunks/src_lib_ea5dd9ae._.js")
R.c("server/chunks/_0400d752._.js")
R.c("server/chunks/[root-of-the-server]__3026ce34._.js")
R.c("server/chunks/node_modules_@upstash_redis_nodejs_mjs_85cd95da._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/src_8328a50c._.js")
R.c("server/chunks/_next-internal_server_app_api_search_route_actions_4244da48.js")
R.m(62518)
module.exports=R.m(62518).exports
