var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/email/route.js")
R.c("server/chunks/[root-of-the-server]__6575fad8._.js")
R.c("server/chunks/_f15003fe._.js")
R.c("server/chunks/[root-of-the-server]__e9a808e4._.js")
R.c("server/chunks/[root-of-the-server]__b3b04900._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__e48e7fd3._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_email_route_actions_02c4a2f1.js")
R.m(20194)
module.exports=R.m(20194).exports
